version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - node/install:
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Install Front-End Dependencies
          command: |
            npm run frontend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Front-End Test
          command: |
            npm run frontend:test
      - run:
          name: Front-End E2E test
          command: |
            npm run frontend:e2e
      - checkout
      - run:
          name: Install Backend API Dependencies
          command: |
            npm run api:install
      - run:
          name: Backend API Build
          command: |
            npm run api:build
            
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - run:
          name: Backend API Deployment
          command: |
            npm run api:deploy
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy

workflows:
  udagram:
    jobs:
      - build
      - deploy

